SELECT distinct 
AGIS_OBJECT.GIS_ID, 
AGIS_OBJECT.GIS_TYPE_ID, 
AGIS_OBJECT.GIS_SERVICE_ID, 
AGIS_OBJECT.OBJECT_ID, 
AGIS_OBJECT.REC_DATE, 
AGIS_OBJECT.REC_FUL_NAM, 
AGIS_OBJECT.REC_STATUS, 
B1_APPL_STATUS as LABEL_FIELD 
FROM AGIS_OBJECT, AGIS_OBJECT_ENT, B1PERMIT
WHERE AGIS_OBJECT.GIS_SERVICE_ID = 'HARVEY' 
AND AGIS_OBJECT_ENT.AGENCY='77001' 
AND AGIS_OBJECT_ENT.ENT_TYPE='APPLICATION' 
AND AGIS_OBJECT_ENT.AGENCY=AGIS_OBJECT.AGENCY 
AND AGIS_OBJECT_ENT.OBJECT_ID=AGIS_OBJECT.OBJECT_ID 
AND AGIS_OBJECT_ENT.B1_PER_ID1=B1PERMIT.B1_PER_ID1 
AND AGIS_OBJECT_ENT.B1_PER_ID2=B1PERMIT.B1_PER_ID2 
AND AGIS_OBJECT_ENT.B1_PER_ID3=B1PERMIT.B1_PER_ID3 
AND AGIS_OBJECT_ENT.ENT_ID='NONE' 
AND B1PERMIT.SERV_PROV_CODE='HARVEY' 
AND B1PERMIT.B1_PER_SUB_TYPE = 'Occupied Structure'
AND B1PERMIT.B1_APPL_STATUS = 'Completed - Green'