



  CREATE OR REPLACE FORCE VIEW "ACCELA"."V_REF_CONTACT_COND" ("AGENCY_ID", "UPDATED_BY", "UPDATED_DATE", "ADDRESS_LINE1", "ADDRESS_LINE2", "ADDRESS_LINE3", "ADDRESS_CITY", "ADDRESS_PO_BOX", "ADDRESS_STATE", "ADDRESS_ZIP", "ADDRESS_COUNTRY", "BUSINESS_NAME", "CONTACT_REF_ID", "CONTACT_TYPE", "EMAIL", "FAX", "FAX_COUNTRY_CODE", "FEIN", "GENDER", "NAME_FIRST", "NAME_MIDDLE", "NAME_LAST", "NAME_FML#", "NAME_FULL", "PHONE1", "PHONE1_COUNTRY_CODE", "PHONE2", "PHONE2_COUNTRY_CODE", "PHONE3", "PHONE3_COUNTRY_CODE", "PREFERRED_CHANNEL", "PRIMARY_", "RELATIONSHIP", "SALUTATION", "STATUS", "TITLE", "TRADE_NAME", "TEMPLATE_ID", "T_ID1"
  ,"COND_UPDATED_BY", "COND_UPDATED_DATE", 
  "SOURCE_SEQ_NBR", "ENTITY_TYPE", "ENTITY_ID", "COND_NBR", "COND_COMMENT", "COND_DES", 
  "EFFECTIVE_DATE", "EXPIRATION_DATE", "ISSUED_DATE", "ISSUED_BY_FNAME", "ISSUED_BY_LNAME", "STATUS_DATE", 
  "COND_STATUS", "COND_TYPE", "LONG_COMMENT", "STATUS_TYPE", "COND_GROUP", "DISP_NOTICE") AS 
  SELECT
  B.SERV_PROV_CODE                  AS AGENCY_ID
--=== Row Update Info
  ,B.REC_FUL_NAM                    AS UPDATED_BY
  ,B.REC_DATE                       AS UPDATED_DATE
--=== Reference Contact Info  
  ,B.G1_ADDRESS1                    AS ADDRESS_LINE1
  ,B.G1_ADDRESS2                    AS ADDRESS_LINE2
  ,B.G1_ADDRESS3                    AS ADDRESS_LINE3
  ,B.G1_CITY                        AS ADDRESS_CITY
  ,B.L1_POST_OFFICE_BOX             AS ADDRESS_PO_BOX
  ,B.G1_STATE                       AS ADDRESS_STATE
  ,B.G1_ZIP                         AS ADDRESS_ZIP
  ,B.G1_COUNTRY                     AS ADDRESS_COUNTRY
  ,B.G1_BUSINESS_NAME               AS BUSINESS_NAME  
  ,B.G1_CONTACT_NBR                 AS CONTACT_REF_ID
  ,B.G1_CONTACT_TYPE                AS CONTACT_TYPE
  ,B.G1_EMAIL                       AS EMAIL  
  ,B.G1_FAX                         AS FAX  
  ,B.G1_FAX_COUNTRY_CODE            AS FAX_COUNTRY_CODE
  ,B.G1_FEDERAL_EMPLOYER_ID_NUM     AS FEIN  
  ,B.L1_GENDER                      AS GENDER
  ,B.G1_FNAME                       AS NAME_FIRST
  ,B.G1_MNAME                       AS NAME_MIDDLE
  ,B.G1_LNAME                       AS NAME_LAST
  ,(
    B.G1_FNAME||' '||
    (CASE WHEN B.G1_MNAME IS NOT NULL THEN B.G1_MNAME||' ' ELSE '' END)||
    B.G1_LNAME
  )                               AS NAME_FML#
  ,B.G1_FULL_NAME                   AS NAME_FULL
  ,B.G1_PHONE1                      AS PHONE1
  ,B.G1_PHONE1_COUNTRY_CODE         AS PHONE1_COUNTRY_CODE
  ,B.G1_PHONE2                      AS PHONE2
  ,B.G1_PHONE2_COUNTRY_CODE         AS PHONE2_COUNTRY_CODE
  ,B.G1_PHONE3                      AS PHONE3
  ,B.G1_PHONE3_COUNTRY_CODE         AS PHONE3_COUNTRY_CODE
    ,(  CASE 
        WHEN B.G1_PREFERRED_CHANNEL=0 OR B.G1_PREFERRED_CHANNEL IS NULL
          THEN ''
        ELSE COALESCE(C1.VALUE_DESC,C2.VALUE_DESC)
      END    
  )	                              AS PREFERRED_CHANNEL
  ,coalesce(B.G1_FLAG,'N')        AS PRIMARY_
  ,B.G1_RELATION                  AS RELATIONSHIP  
  ,B.L1_SALUTATION                AS SALUTATION
  ,B.REC_STATUS	                  AS STATUS  
  ,B.G1_TITLE                     AS TITLE
  ,B.G1_TRADE_NAME                AS TRADE_NAME  
---- column to support build relation with Templates.
  ,TO_CHAR(B.G1_CONTACT_NBR)               AS TEMPLATE_ID
  ,TO_CHAR(B.G1_CONTACT_NBR) AS T_ID1  
---- CONDITIONS
  ,B1.REC_FUL_NAM                    AS COND_UPDATED_BY
  ,B1.REC_DATE                       AS COND_UPDATED_DATE
  ,B1.SOURCE_SEQ_NBR                    AS SOURCE_SEQ_NBR
  ,B1.L1_ENTITY_TYPE                    AS ENTITY_TYPE
  ,B1.L1_ENTITY_ID                    AS ENTITY_ID
  ,B1.L1_CON_NBR                        AS COND_NBR
  ,B1.L1_CON_COMMENT             AS COND_COMMENT
  ,B1.L1_CON_DES                       AS COND_DES
  ,B1.L1_CON_EFF_DD1                     AS EFFECTIVE_DATE
  ,B1.L1_CON_EXPIR_DD               AS EXPIRATION_DATE  
  ,B1.L1_CON_ISS_DD  AS ISSUED_DATE
  ,B1.L1_CON_ISS_FNAME AS ISSUED_BY_FNAME
  ,B1.L1_CON_ISS_LNAME AS ISSUED_BY_LNAME
  ,B1.L1_CON_STAT_DD AS STATUS_DATE
  ,B1.L1_CON_STATUS AS COND_STATUS
  ,B1.L1_CON_TYP AS COND_TYPE
  ,B1.L1_CON_LONG_COMMENT AS LONG_COMMENT
  ,B1.L1_CON_STATUS_TYP AS STATUS_TYPE
  ,B1.L1_CON_GROUP AS COND_GROUP
  ,B1.L1_CON_DIS_CON_NOTICE AS DISP_NOTICE
FROM
  G3CONTACT B
  LEFT JOIN
  RBIZDOMAIN_VALUE C1
    ON  B.SERV_PROV_CODE=C1.SERV_PROV_CODE
    AND C1.BIZDOMAIN='CONTACT_PREFERRED_CHANNEL'
    AND B.G1_PREFERRED_CHANNEL=C1.BIZDOMAIN_VALUE
    AND C1.REC_STATUS='A'
  LEFT JOIN
  RBIZDOMAIN_VALUE C2
    ON  C2.SERV_PROV_CODE='STANDARDDATA'
    AND C2.BIZDOMAIN='CONTACT_PREFERRED_CHANNEL'
    AND B.G1_PREFERRED_CHANNEL=C2.BIZDOMAIN_VALUE
    AND C2.REC_STATUS='A'
  LEFT OUTER JOIN
  L3COMMON_CONDIT B1
    ON B1.SERV_PROV_CODE=B.SERV_PROV_CODE
    AND B1.L1_ENTITY_ID = B.G1_CONTACT_NBR;


